services:
  mysql:
    image: mysql:8.0
    container_name: mysql_fitchain
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_fitchain
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  reserva:
    build: .
    container_name: reserva_service
    restart: always
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_fitchain
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
