server.port=8087
spring.application.name=reserva

spring.datasource.url=jdbc:mysql://localhost:3306/db_fitchain
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cliente.service.url=${CLIENTE_SERVICE_URL:http://localhost:8081}
horario.service.url=${HORARIO_SERVICE_URL:http://localhost:8086}

#VARIABLES DE ENTORNO AL FINAL, OJALÁ FUNCIONE

#Lo del swagger
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs

#Opcional
spring.hateoas.use-hal-as-default-json-media-type=true